### ISSUE TITLE
不能运行？

### ISSUE THREAD

**Issue by zuowanbushiwo** [waterfoxfox/Audio3AProcess#1]
在vs2019 上 x86 release 能编译通过，但是运行失败。

**Comment by waterfoxfox** [comment]
应该是授权已经到期了，有需要可以加QQ 1821554146 获取新版
















在 2022-05-20 19:38:30，"zuowanbushiwo" ***@***.***> 写道：

在vs2019 上 x86 release 能编译通过，但是运行失败。

**Comment by waterfoxfox** [comment]
新提交版本已更新授权
